database_connection:
    host: 127.0.0.1
    port: 3306
    user: root
    password: "123456"
server:
    port: :8888
database_names:
    admin_db: schoolbus
    passenger_db: passenger_db
    driver_db: driver_db
jwt:
    expiration_hours_passenger: 24
    expiration_hours_admin: 99999
    expiration_hours_driver: 128
other:
    expiration_ride_coupon: 30
    api_key: null
